<?php

return [
    [
        'key'  => 'catalog.products.ai_review',
        'name' => 'AI Review',
        'info' => 'Settings for automated product reviews generation.',
        'sort' => 80,
        'fields' => [
            [
                'name'          => 'enabled',
                'title'         => 'Enable AI Review',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'default_status',
                'title'         => 'Default Status',
                'type'          => 'select',
                'options'       => [
                    ['title' => 'approved',   'value' => 'approved'],
                    ['title' => 'pending',    'value' => 'pending'],
                ],
                'default'       => 'pending',
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'max_reviews_per_product',
                'title'         => 'Max Reviews per Product',
                'type'          => 'number',
                'validation'    => 'min:1',
                'default'       => 10,
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'min_rating',
                'title'         => 'Min Rating',
                'type'          => 'number',
                'validation'    => 'min:1|max:5',
                'default'       => 4,
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'max_rating',
                'title'         => 'Max Rating',
                'type'          => 'number',
                'validation'    => 'min:1|max:5',
                'default'       => 5,
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'use_openai',
                'title'         => 'Use OpenAI',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'openai_api_key',
                'title'         => 'OpenAI API Key',
                'type'          => 'text',
                'default'       => '',
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'review_templates',
                'title'         => 'Review Templates (one per line)',
                'type'          => 'textarea',
                'default'       => "Great quality and fast delivery!\nImpressed with the build and value.",
                'channel_based' => false,
                'locale_based'  => false,
            ],
            [
                'name'          => 'auto_generate_on_product_import',
                'title'         => 'Auto-generate on Product Import',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => false,
                'locale_based'  => false,
            ],
        ],
    ],
];