<?php

use Webkul\Sales\Models\Order;

return [
    [
        'key'    => 'sales.payment_methods.airwallex',
        'name'   => 'airwallex::app.admin.system.title',
        'info'   => 'airwallex::app.admin.system.description',
        'sort'   => 5,
        'fields' => [
            [
                'name'          => 'title',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.title',
                'type'          => 'text',
                'depends'       => 'active:1',
                'validation'    => 'required_if:active,1',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'description',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.description',
                'type'          => 'textarea',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'image',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.logo',
                'type'          => 'image',
                'info'          => 'admin::app.configuration.index.sales.payment-methods.logo-information',
                'channel_based' => true,
                'locale_based'  => false,
                'validation'    => 'mimes:bmp,jpeg,jpg,png,webp',
            ], [
                'name'          => 'client_id',
                'title'         => 'airwallex::app.admin.system.client-id',
                'type'          => 'text',
                'depends'       => 'active:1',
                'validation'    => 'required_if:active,1',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'api_key',
                'title'         => 'airwallex::app.admin.system.api-key',
                'type'          => 'password',
                'depends'       => 'active:1',
                'validation'    => 'required_if:active,1',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'merchant_id',
                'title'         => 'airwallex::app.admin.system.merchant-id',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'base_url',
                'title'         => 'airwallex::app.admin.system.base-url',
                'type'          => 'text',
                'validation'    => 'required_if:active,1|url',
                'channel_based' => true,
                'locale_based'  => false,
                'default_value' => 'https://api.airwallex.com',
            ], [
                'name'          => 'sandbox',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.sandbox',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
                'default_value' => true,
            ], [
                'name'          => 'callback_url',
                'title'         => 'airwallex::app.admin.system.callback-url',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'use_hpp',
                'title'         => 'Use Hosted Payment Page',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
                'default_value' => false,
            ], [
                'name'          => 'debug',
                'title'         => 'airwallex::app.admin.system.debug',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
                'default_value' => false,
            ], [
                'name'          => 'webhook_secret',
                'title'         => 'airwallex::app.admin.system.webhook-secret',
                'type'          => 'password',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'currency',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.currency',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
                'default_value' => 'USD',
            ], [
                'name'          => 'methods',
                'title'         => 'airwallex::app.admin.system.methods',
                'type'          => 'text',
                'depends'       => 'active:1',
                'channel_based' => true,
                'locale_based'  => false,
                'default_value' => 'card,applepay,googlepay,paypal,skrill',
            ], [
                'name'          => 'order_status',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.set-order-status',
                'type'          => 'select',
                'options'       => [
                    ['title' => 'admin::app.configuration.index.sales.payment-methods.pending', 'value' => Order::STATUS_PENDING],
                    ['title' => 'admin::app.configuration.index.sales.payment-methods.pending-payment', 'value' => Order::STATUS_PENDING_PAYMENT],
                    ['title' => 'admin::app.configuration.index.sales.payment-methods.processing', 'value' => Order::STATUS_PROCESSING],
                ],
                'info'          => 'admin::app.configuration.index.sales.payment-methods.generate-invoice-applicable',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'active',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.status',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'sort',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.sort-order',
                'type'          => 'select',
                'options'       => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                ],
                'channel_based' => true,
                'locale_based'  => false,
            ],
        ],
    ],
];
